### ISSUE TITLE
How to get partial pattern of nested routes

### ISSUE THREAD

**Issue by Djaler** [leancodepl/ts-routes#18]
Given
```
const routes = createRouting({
    parent: {
        ...segment`/user/${number('userId')}`,
        children: {
            foo: segment`/foo`
            bar: segment`/bar`,
        },
    },
} as const);
```

In vue router config I have something like
```
const router = new VueRouter({
  routes: [
    {
      path: '/user/:userId',
      component: User,
      children: [
        {
          path: 'foo',
          component: Foo
        },
        {
          path: 'bar',
          component: Bar
        }
      ]
    }
  ]
})
```

I can replace `'/user/:userId'` with `routes.user.pattern`, but how can I replace paths for nested routes in vue router config?
I need to somehow get `/foo` but `routes.user.foo.pattern` returns `/user/:userId/foo`

**Comment by Djaler** [comment]
Update: looks like vue router works good even when I use not partial path for nested route:
```
const router = new VueRouter({
  routes: [
    {
      path: '/user/:userId',
      component: User,
      children: [
        {
          path: '/user/:userId/foo',
          component: Foo
        },
        {
          path: '/user/:userId/bar',
          component: Bar
        }
      ]
    }
  ]
})
```

So, looks like I can use just `routes.user.foo.pattern`

**Comment by konowrockis** [comment]
Hi, sorry for the delay with the response but I was on vacation :)

Glad you've resolved the issue. I haven't tinkered that much with the vue router. I think I'll add that do the docs if you don't mind.

Thanks!
