### ISSUE TITLE
VSCode falsely reports type errors

### ISSUE THREAD

**Issue by mchudy** [leancodepl/ts-routes#9]
VSCode Version: 1.56.2

Looks like a bug in the VSCode TS engine, but worth tracking the status here. Build and tests pass, so it's not a TypeScript issue.

![Screen Shot 2021-05-19 at 13 27 53](https://user-images.githubusercontent.com/9952229/118805654-77449f80-b8a6-11eb-880d-c4c90ba5e70d.png)

**Comment by konowrockis** [comment]
I think I've seen this one.
Not sure if something hasn't changed between TS version's and maybe TS in the new VSCode has been updated?
On which version of TS have you checked that?

**Comment by mchudy** [comment]
I checked both the one from the project and the latest one. @marcin-dardzinski had this problem in his project and apparently downgrading TS has helped. However, this hasn't been the case for me when I opened the ts-routes project.

**Comment by marcin-dardzinski** [comment]
For me it was not only vs code failing, the app itself didn't compile (on 4.2.4). For 4.1.5 it compiles, vs code works too. I can send you the repro project later if you want.

**Comment by konowrockis** [comment]
I think we had the same case in prosp. Need to check how it behaves in different TS versions.
